In [32]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in c:\users\sathi\appdata\roaming\python\python313\site-packages (3.4.1)
Requirement already satisfied: numpy in c:\anaconda 3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\anaconda 3\lib\site-packages (from xgboost) (1.15.3)

In [33]:
import xgboost as xgb

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
dataset = pd.read_csv('CKD.csv')

In [36]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [37]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [38]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [39]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [40]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [41]:
independent= dataset [['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [42]:
dependent=dataset [['classification_yes']]

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [45]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {
        'min_child_weight': [1, 5, 10],
        'gamma': [0.5, 1, 1.5, 2, 5],
        'subsample': [0.6, 0.8, 1.0],
        'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3, 4, 5]
        }    
grid = GridSearchCV(XGBClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 405 candidates, totalling 2025 fits

GridSearchCV(estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=True, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     lear...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.6, 0.8, 1.0],
                         'gamma': [0.5, 1, 1.5, 2, 5], 'max_depth': [3, 4, 5],
                         'min_child_weight': [1, 5, 10],
                         'subsample': [0.6, 0.8, 1.0]},
             verbose=3)

In [46]:
re=grid.cv_results_

grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

C:\Anaconda 3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Anaconda 3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Anaconda 3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [47]:
print(grid.best_params_)

{'colsample_bytree': 0.6, 'gamma': 1, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 1.0}

In [48]:
table=pd.DataFrame.from_dict(re)

In [49]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_colsample_bytree,param_gamma,param_max_depth,param_min_child_weight,param_subsample,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.353034,0.001766,0.026125,0.000165,0.6,0.5,3,1,0.6,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.9000,0.9875,0.9625,1.0000,1.000000,0.970000,0.037583,51
1,0.345441,0.009968,0.025309,0.001904,0.6,0.5,3,1,0.8,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.9000,0.9875,0.9625,1.0000,1.000000,0.970000,0.037583,51
2,0.329253,0.006069,0.023817,0.002777,0.6,0.5,3,1,1.0,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.9250,1.0000,0.9625,0.9875,1.000000,0.975000,0.028504,14
3,0.292827,0.017400,0.021124,0.001598,0.6,0.5,3,5,0.6,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.8625,0.9875,0.9500,0.9625,0.987342,0.949968,0.046072,187
4,0.282445,0.004112,0.021490,0.002168,0.6,0.5,3,5,0.8,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.8750,0.9875,0.9500,0.9625,0.987342,0.952468,0.041356,164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,0.367312,0.031227,0.031024,0.011392,1.0,5.0,5,5,0.8,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8625,0.9875,0.9250,0.9625,0.987342,0.944968,0.047141,235
401,0.409399,0.028764,0.023429,0.003512,1.0,5.0,5,5,1.0,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8750,0.9875,0.9250,0.9625,0.987342,0.947468,0.042837,214
402,0.412735,0.050191,0.029039,0.010500,1.0,5.0,5,10,0.6,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8750,0.9750,0.8750,0.9500,1.000000,0.935000,0.051478,310
403,0.390814,0.053017,0.020665,0.007098,1.0,5.0,5,10,0.8,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8375,0.9875,0.9000,0.9625,0.987342,0.934968,0.058281,328
404,0.310556,0.044058,0.016963,0.002028,1.0,5.0,5,10,1.0,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8875,0.9875,0.9000,0.9625,0.987342,0.944968,0.042980,238

In [50]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'colsample_bytree': 0.6, 'gamma': 1, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 1.0}: 0.4702920090924987

In [51]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[ 0 51]
 [ 0 82]]

In [52]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        51
           1       0.62      1.00      0.76        82

    accuracy                           0.62       133
   macro avg       0.31      0.50      0.38       133
weighted avg       0.38      0.62      0.47       133

In [53]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

np.float64(0.9899569583931134)

In [54]:
table=pd.DataFrame.from_dict(re)

In [55]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_colsample_bytree,param_gamma,param_max_depth,param_min_child_weight,param_subsample,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.353034,0.001766,0.026125,0.000165,0.6,0.5,3,1,0.6,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.9000,0.9875,0.9625,1.0000,1.000000,0.970000,0.037583,51
1,0.345441,0.009968,0.025309,0.001904,0.6,0.5,3,1,0.8,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.9000,0.9875,0.9625,1.0000,1.000000,0.970000,0.037583,51
2,0.329253,0.006069,0.023817,0.002777,0.6,0.5,3,1,1.0,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.9250,1.0000,0.9625,0.9875,1.000000,0.975000,0.028504,14
3,0.292827,0.017400,0.021124,0.001598,0.6,0.5,3,5,0.6,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.8625,0.9875,0.9500,0.9625,0.987342,0.949968,0.046072,187
4,0.282445,0.004112,0.021490,0.002168,0.6,0.5,3,5,0.8,"{'colsample_bytree': 0.6, 'gamma': 0.5, 'max_d...",0.8750,0.9875,0.9500,0.9625,0.987342,0.952468,0.041356,164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,0.367312,0.031227,0.031024,0.011392,1.0,5.0,5,5,0.8,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8625,0.9875,0.9250,0.9625,0.987342,0.944968,0.047141,235
401,0.409399,0.028764,0.023429,0.003512,1.0,5.0,5,5,1.0,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8750,0.9875,0.9250,0.9625,0.987342,0.947468,0.042837,214
402,0.412735,0.050191,0.029039,0.010500,1.0,5.0,5,10,0.6,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8750,0.9750,0.8750,0.9500,1.000000,0.935000,0.051478,310
403,0.390814,0.053017,0.020665,0.007098,1.0,5.0,5,10,0.8,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8375,0.9875,0.9000,0.9625,0.987342,0.934968,0.058281,328
404,0.310556,0.044058,0.016963,0.002028,1.0,5.0,5,10,1.0,"{'colsample_bytree': 1.0, 'gamma': 5, 'max_dep...",0.8875,0.9875,0.9000,0.9625,0.987342,0.944968,0.042980,238

In [56]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("Sg B 0 OR 1:"))
sg_c_input=float(input("Sg C 0 OR 1:"))
sg_d_input=float(input("Sg D 0 OR 1:"))
sg_e_input=float(input("Sg E 0 OR 1:"))
rbc_normal_input=float(input("Rbc Normal 0 or 1:"))
pc_normal_input=float(input("Pc Normal 0 or 1:"))
pcc_present_input=float(input("Pcc Present 0 or 1:"))
ba_present_input=float(input("Ba Present 0 or 1:"))
htn_yes_input=float(input("Htn Yes 0 or 1:"))
dm_yes_input=float(input("Dm Yes 0 or 1:"))
cad_yes_input=float(input("Cad Yes 0 or 1:"))
appet_yes_input=float(input("Appet Yes 0 or 1:"))
pe_yes_input=float(input("Pe Yes 0 or 1:"))
ane_yes_input=float(input("Ane Yes 0 or 1:"))

Age: 45
BP: 65
AL: 34
SU: 76
BGR: 87
BU: 46
SC: 54
SOD: 34
POT: 22
HRMO: 56
PCV: 45
WC: 76
RC: 58
Sg B 0 OR 1: 1
Sg C 0 OR 1: 0
Sg D 0 OR 1: 1
Sg E 0 OR 1: 0
Rbc Normal 0 or 1: 1
Pc Normal 0 or 1: 0
Pcc Present 0 or 1: 1
Ba Present 0 or 1: 0
Htn Yes 0 or 1: 1
Dm Yes 0 or 1: 0
Cad Yes 0 or 1: 1
Appet Yes 0 or 1: 0
Pe Yes 0 or 1: 1
Ane Yes 0 or 1: 0

In [57]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

In [58]:
import pickle
filename="finalized_model_XGBoost_GridSearchCV.sav"
pickle.dump(grid,open(filename, 'wb'))

In [59]:
preinput=sc.transform([[99,37,86,45,90,29,61,50,39,44,56,27,66,1,0,1,0,1,0,1,0,1,0,1,0,1,0]])

C:\Anaconda 3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [60]:
preinput

array([[ 2.87569868, -3.0468519 , 69.15359897, 45.03417   , -0.78131471,
        -0.59027585,  9.73410043, -8.31542838, 15.46938388, 11.65952127,
         2.09259632, -3.45368838, 75.12919293,  2.02864108, -0.5454915 ,
         2.21610269, -0.13840913,  0.38924947, -1.95866374,  2.91547595,
        -0.23570226,  1.35269628, -0.73926425,  3.41565026, -1.93649167,
         1.91485422, -0.44519456]])

In [61]:
loaded_model=pickle.load(open("finalized_model_XGBoost_GridSearchCV.sav", 'rb'))
result=loaded_model.predict(preinput)
result

array([1])

In [62]:
def inverse_transform_dummies_with_if(array):
      result = np.array([0])

if np.array_equal(result, np.array([0])):
    print("No")
else:
    print("Yes")

Yes