In [31]:
pip install lightgbm==3.3.5

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: lightgbm==3.3.5 in c:\users\sathi\appdata\roaming\python\python313\site-packages (3.3.5)
Requirement already satisfied: wheel in c:\anaconda 3\lib\site-packages (from lightgbm==3.3.5) (0.45.1)
Requirement already satisfied: numpy in c:\anaconda 3\lib\site-packages (from lightgbm==3.3.5) (2.1.3)
Requirement already satisfied: scipy in c:\anaconda 3\lib\site-packages (from lightgbm==3.3.5) (1.15.3)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\anaconda 3\lib\site-packages (from lightgbm==3.3.5) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in c:\anaconda 3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm==3.3.5) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\anaconda 3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm==3.3.5) (3.5.0)

In [32]:
import lightgbm as lgb

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [34]:
dataset = pd.read_csv('CKD.csv')

In [35]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [36]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [37]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [38]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [39]:
independent= dataset [['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [40]:
dependent=dataset [['classification_yes']]

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [43]:
from lightgbm import LGBMClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {
        
"num_leaves": [31, 63, 127],
"max_depth": [-1, 3, 5],
"subsample": [0.8, 1.0],
"colsample_bytree": [0.8, 1.0]

        }    
grid = GridSearchCV(LGBMClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Anaconda 3\Lib\site-packages\sklearn\preprocessing\_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda 3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

GridSearchCV(estimator=LGBMClassifier(), n_jobs=-1,
             param_grid={'colsample_bytree': [0.8, 1.0],
                         'max_depth': [-1, 3, 5], 'num_leaves': [31, 63, 127],
                         'subsample': [0.8, 1.0]},
             verbose=3)

In [44]:
re=grid.cv_results_

grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

C:\Anaconda 3\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Anaconda 3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Anaconda 3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Anaconda 3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [45]:
print(grid.best_params_)

{'colsample_bytree': 0.8, 'max_depth': -1, 'num_leaves': 31, 'subsample': 0.8}

In [46]:
table=pd.DataFrame.from_dict(re)

In [47]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_colsample_bytree,param_max_depth,param_num_leaves,param_subsample,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.135598,0.002819,0.013162,0.001378,0.8,-1,31,0.8,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
1,0.110384,0.031131,0.012085,0.001229,0.8,-1,31,1.0,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
2,0.079737,0.005279,0.011580,0.001333,0.8,-1,63,0.8,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
3,0.077819,0.001812,0.010623,0.000762,0.8,-1,63,1.0,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
4,0.071652,0.002486,0.008891,0.002511,0.8,-1,127,0.8,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
5,0.072508,0.002242,0.010858,0.000459,0.8,-1,127,1.0,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
6,0.048384,0.002662,0.011460,0.001702,0.8,3,31,0.8,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
7,0.048325,0.001500,0.012445,0.001182,0.8,3,31,1.0,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
8,0.054108,0.001138,0.010411,0.000841,0.8,3,63,0.8,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
9,0.051265,0.002764,0.012202,0.001091,0.8,3,63,1.0,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
10,0.055734,0.003262,0.013388,0.001415,0.8,3,127,0.8,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
11,0.056851,0.002434,0.011529,0.001582,0.8,3,127,1.0,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
12,0.066349,0.003166,0.010107,0.000834,0.8,5,31,0.8,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
13,0.065530,0.002769,0.011252,0.001584,0.8,5,31,1.0,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
14,0.062529,0.001237,0.010818,0.000864,0.8,5,63,0.8,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
15,0.067428,0.006252,0.012872,0.002760,0.8,5,63,1.0,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
16,0.077807,0.007674,0.012759,0.002660,0.8,5,127,0.8,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
17,0.078830,0.005946,0.010851,0.000686,0.8,5,127,1.0,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
18,0.092810,0.005998,0.011519,0.000402,1.0,-1,31,0.8,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
19,0.089612,0.008288,0.013999,0.004968,1.0,-1,31,1.0,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
20,0.083357,0.005897,0.013808,0.004812,1.0,-1,63,0.8,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
21,0.095718,0.015963,0.011861,0.002502,1.0,-1,63,1.0,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
22,0.097419,0.017361,0.013203,0.002541,1.0,-1,127,0.8,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
23,0.090821,0.002833,0.011415,0.001420,1.0,-1,127,1.0,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
24,0.063053,0.009296,0.013464,0.004816,1.0,3,31,0.8,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
25,0.051701,0.004104,0.011143,0.000791,1.0,3,31,1.0,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
26,0.052530,0.001303,0.010254,0.001222,1.0,3,63,0.8,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
27,0.049381,0.002661,0.010764,0.000792,1.0,3,63,1.0,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
28,0.048483,0.002737,0.010441,0.001422,1.0,3,127,0.8,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
29,0.049518,0.001923,0.010372,0.001404,1.0,3,127,1.0,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
30,0.070203,0.010086,0.011622,0.002144,1.0,5,31,0.8,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
31,0.070583,0.004953,0.012507,0.001855,1.0,5,31,1.0,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
32,0.077272,0.007505,0.011137,0.001364,1.0,5,63,0.8,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
33,0.072489,0.004854,0.009873,0.000901,1.0,5,63,1.0,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
34,0.068755,0.004039,0.011723,0.001742,1.0,5,127,0.8,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
35,0.063241,0.005322,0.009115,0.001581,1.0,5,127,1.0,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13

In [48]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'colsample_bytree': 0.8, 'max_depth': -1, 'num_leaves': 31, 'subsample': 0.8}: 0.4702920090924987

In [49]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[ 0 51]
 [ 0 82]]

In [50]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        51
           1       0.62      1.00      0.76        82

    accuracy                           0.62       133
   macro avg       0.31      0.50      0.38       133
weighted avg       0.38      0.62      0.47       133

In [51]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

C:\Anaconda 3\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

np.float64(0.9966523194643712)

In [52]:
table=pd.DataFrame.from_dict(re)

In [53]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_colsample_bytree,param_max_depth,param_num_leaves,param_subsample,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.135598,0.002819,0.013162,0.001378,0.8,-1,31,0.8,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
1,0.110384,0.031131,0.012085,0.001229,0.8,-1,31,1.0,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
2,0.079737,0.005279,0.011580,0.001333,0.8,-1,63,0.8,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
3,0.077819,0.001812,0.010623,0.000762,0.8,-1,63,1.0,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
4,0.071652,0.002486,0.008891,0.002511,0.8,-1,127,0.8,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
5,0.072508,0.002242,0.010858,0.000459,0.8,-1,127,1.0,"{'colsample_bytree': 0.8, 'max_depth': -1, 'nu...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
6,0.048384,0.002662,0.011460,0.001702,0.8,3,31,0.8,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
7,0.048325,0.001500,0.012445,0.001182,0.8,3,31,1.0,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
8,0.054108,0.001138,0.010411,0.000841,0.8,3,63,0.8,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
9,0.051265,0.002764,0.012202,0.001091,0.8,3,63,1.0,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
10,0.055734,0.003262,0.013388,0.001415,0.8,3,127,0.8,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
11,0.056851,0.002434,0.011529,0.001582,0.8,3,127,1.0,"{'colsample_bytree': 0.8, 'max_depth': 3, 'num...",0.9125,1.0,1.0000,0.9875,1.0,0.9800,0.034095,31
12,0.066349,0.003166,0.010107,0.000834,0.8,5,31,0.8,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
13,0.065530,0.002769,0.011252,0.001584,0.8,5,31,1.0,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
14,0.062529,0.001237,0.010818,0.000864,0.8,5,63,0.8,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
15,0.067428,0.006252,0.012872,0.002760,0.8,5,63,1.0,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
16,0.077807,0.007674,0.012759,0.002660,0.8,5,127,0.8,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
17,0.078830,0.005946,0.010851,0.000686,0.8,5,127,1.0,"{'colsample_bytree': 0.8, 'max_depth': 5, 'num...",0.9750,1.0,0.9875,0.9875,1.0,0.9900,0.009354,1
18,0.092810,0.005998,0.011519,0.000402,1.0,-1,31,0.8,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
19,0.089612,0.008288,0.013999,0.004968,1.0,-1,31,1.0,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
20,0.083357,0.005897,0.013808,0.004812,1.0,-1,63,0.8,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
21,0.095718,0.015963,0.011861,0.002502,1.0,-1,63,1.0,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
22,0.097419,0.017361,0.013203,0.002541,1.0,-1,127,0.8,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
23,0.090821,0.002833,0.011415,0.001420,1.0,-1,127,1.0,"{'colsample_bytree': 1.0, 'max_depth': -1, 'nu...",0.9625,1.0,0.9750,0.9875,1.0,0.9850,0.014577,19
24,0.063053,0.009296,0.013464,0.004816,1.0,3,31,0.8,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
25,0.051701,0.004104,0.011143,0.000791,1.0,3,31,1.0,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
26,0.052530,0.001303,0.010254,0.001222,1.0,3,63,0.8,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
27,0.049381,0.002661,0.010764,0.000792,1.0,3,63,1.0,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
28,0.048483,0.002737,0.010441,0.001422,1.0,3,127,0.8,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
29,0.049518,0.001923,0.010372,0.001404,1.0,3,127,1.0,"{'colsample_bytree': 1.0, 'max_depth': 3, 'num...",0.9375,1.0,1.0000,0.9875,1.0,0.9850,0.024238,19
30,0.070203,0.010086,0.011622,0.002144,1.0,5,31,0.8,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
31,0.070583,0.004953,0.012507,0.001855,1.0,5,31,1.0,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
32,0.077272,0.007505,0.011137,0.001364,1.0,5,63,0.8,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
33,0.072489,0.004854,0.009873,0.000901,1.0,5,63,1.0,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
34,0.068755,0.004039,0.011723,0.001742,1.0,5,127,0.8,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13
35,0.063241,0.005322,0.009115,0.001581,1.0,5,127,1.0,"{'colsample_bytree': 1.0, 'max_depth': 5, 'num...",0.9625,1.0,0.9875,0.9875,1.0,0.9875,0.013693,13

In [54]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("Sg B 0 OR 1:"))
sg_c_input=float(input("Sg C 0 OR 1:"))
sg_d_input=float(input("Sg D 0 OR 1:"))
sg_e_input=float(input("Sg E 0 OR 1:"))
rbc_normal_input=float(input("Rbc Normal 0 or 1:"))
pc_normal_input=float(input("Pc Normal 0 or 1:"))
pcc_present_input=float(input("Pcc Present 0 or 1:"))
ba_present_input=float(input("Ba Present 0 or 1:"))
htn_yes_input=float(input("Htn Yes 0 or 1:"))
dm_yes_input=float(input("Dm Yes 0 or 1:"))
cad_yes_input=float(input("Cad Yes 0 or 1:"))
appet_yes_input=float(input("Appet Yes 0 or 1:"))
pe_yes_input=float(input("Pe Yes 0 or 1:"))
ane_yes_input=float(input("Ane Yes 0 or 1:"))

Age: 46
BP: 76
AL: 89
SU: 35
BGR: 65
BU: 34
SC: 37
SOD: 75
POT: 55
HRMO: 45
PCV: 66
WC: 76
RC: 28
Sg B 0 OR 1: 1
Sg C 0 OR 1: 0
Sg D 0 OR 1: 1
Sg E 0 OR 1: 0
Rbc Normal 0 or 1: 1
Pc Normal 0 or 1: 0
Pcc Present 0 or 1: 1
Ba Present 0 or 1: 0
Htn Yes 0 or 1: 1
Dm Yes 0 or 1: 0
Cad Yes 0 or 1: 1
Appet Yes 0 or 1: 0
Pe Yes 0 or 1: 1
Ane Yes 0 or 1: 0

In [55]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

C:\Anaconda 3\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [56]:
import pickle
filename="finalized_model_LGBoost_GridSearchCV.sav"
pickle.dump(grid,open(filename, 'wb'))

In [57]:
preinput=sc.transform([[63,25,50,45,88,98,70,60,21,48,45,77,59,1,0,1,0,1,0,1,0,1,0,1,0,1,0]])

C:\Anaconda 3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [58]:
preinput

array([[ 0.67057466, -3.96991782, 39.91932104, 45.03417   , -0.80753038,
         0.71802458, 11.24986308, -7.36588273,  7.38062207, 13.13886095,
         0.73858714, -3.43285707, 66.55346911,  2.02864108, -0.5454915 ,
         2.21610269, -0.13840913,  0.38924947, -1.95866374,  2.91547595,
        -0.23570226,  1.35269628, -0.73926425,  3.41565026, -1.93649167,
         1.91485422, -0.44519456]])

In [59]:
loaded_model=pickle.load(open("finalized_model_LGBoost_GridSearchCV.sav", 'rb'))
result=loaded_model.predict(preinput)
result

C:\Anaconda 3\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

array([1])

In [60]:
def inverse_transform_dummies_with_if(array):
      result = np.array([0])

if np.array_equal(result, np.array([0])):
    print("No")
else:
    print("Yes")

Yes